version: 2
jobs:
  build-images:
    machine: true
    steps:
      - checkout
      - run: docker build -t levibostian/fastlane:latest fastlane   
      - run: docker build -t levibostian/danger:latest danger
      - run: docker build -t levibostian/pgdump-s3:latest pgdump-s3     
  deploy-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push levibostian/fastlane:latest    
      - run: docker push levibostian/danger:latest     
      - run: docker push levibostian/pgdump-s3:latest     

workflows:
  version: 2
  push:
    jobs:
      - build-images
      
  build-and-deploy:
    jobs:
      - build-images:
          filters:
            branches:
              only: master
      - deploy-images:
          requires: 
            - build-images
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # runs everyday at midnight UTC.
          filters:
            branches:
              only:
                - master
    jobs:
      - build-images
      - deploy-images:
          requires: 
            - build-images

